import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "es" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    "nav.language": "Português",
    "hero.edition": "Edição CDMX",
    "hero.title": "SEO GUACAMOLE",
    "hero.subtitle": "EVENTO",
    "hero.description": "A Conferência de SEO, tacos e tequila, chega ao México.",
    "hero.tagline": "Estratégia, Networking e Café no Rooftop Hotel Roma Conesa.",
    "hero.date": "26 de Fevereiro de 2026",
    "hero.location": "CDMX",
    "hero.price": "",
    "hero.cta.primary": "Comprar Ingresso",
    "hero.cta.secondary": "Saiba mais",
    "about.title": "Sobre o Evento",
    "about.description": "<a href='https://www.linkedin.com/in/nestorvazquez/' rel='follow' target='_blank'>Nestor Vazquez</a> traz para a Cidade do México sua série de eventos internacionais. Esta edição especial, The Guacamole, foi projetada para despertar seus sentidos e sua estratégia.",
    "about.details": "Em colaboração com <a href='https://seoforlatam.com/' rel='follow' target='_blank'>SEO for LATAM Agency</a>, criamos um espaço onde o humano e o artificial convergem. Falaremos sobre o que realmente funciona hoje para classificar no Google e como integrar Inteligência Artificial (IA) em seus fluxos de trabalho. Sem enchimento, apenas táticas acionáveis.",
    "about.speakers": "Palestrantes Especialistas",
    "about.duration": "Horas Intensivas",
    "about.attendees": "Participantes VIP",
    "about.coffee": "Café",
    "speakers.title": "Nossos",
    "speakers.subtitle": "Palestrantes",
    "speakers.aleksandar.title": "Diretor Gerente",
    "speakers.aleksandar.bio": "Aleks Manok Diretor Gerente na Odys Marketplace, especializado em domínios envelhecidos premium e estratégia de ativos digitais focado em ajudar profissionais de SEO a tratar a autoridade como capital desde a aquisição até a monetização e estratégia de saída.",
    "speakers.jimena.title": "Chefe de Marketing",
    "speakers.jimena.bio": "Consultora de Marketing iGaming",
    "speakers.nestor.title": "Mentor e Estrategista",
    "speakers.nestor.bio": "Especialista em SEO Local e Técnico. Domine automação com Python para otimizar processos em mercados competitivos dos EUA.",
    "speakers.eduardo.title": "Líder de Equipe @ WhitePress",
    "speakers.eduardo.bio": "Apaixonado por SEO e música. Lidera estratégias de Link Building e Digital PR que melhoram a visibilidade e autoridade do cliente.",
    "speakers.miguel.title": "Fundador Agencia SEO en Mexico",
    "speakers.miguel.bio": "Consultor de SEO com +10 anos de experiência e host do TOPSEO. Oferece soluções personalizadas para empresas de todos os tamanhos.",
    "speakers.qa.title": "Perguntas Frequentes",
    "faq.title": "Perguntas",
    "faq.subtitle": "Frequentes",
    "faq.description": "Tudo o que você precisa saber sobre o treinamento SEO Guacamole",
    "faq.general.q1": "O treinamento SEO Guacamole é adequado para meu nível de experiência?",
    "faq.general.a1": "SEO Guacamole acolhe profissionais de SEO em todos os níveis—seja você está apenas começando sua jornada ou é um especialista experiente procurando aprimorar suas habilidades. Nestor Vazquez projetou este treinamento com uma missão: guiá-lo para seu próximo nível, onde quer que você esteja agora. Iniciantes ganharão conhecimento fundamental e estratégias comprovadas para construir confiança, enquanto profissionais intermediários e avançados descobrirão táticas de ponta baseadas em testes e resultados do mundo real. Não importa onde você esteja em sua carreira de SEO, Nestor está comprometido em ajudá-lo a evoluir com insights acionáveis que você pode implementar imediatamente.",
    "faq.general.q2": "Qual é a política de reembolso?",
    "faq.general.a2": "Reembolso total disponível até 1º de fevereiro. Basta nos enviar um e-mail e processaremos seu reembolso, sem perguntas. Após 1º de fevereiro, os ingressos são não-reembolsáveis, mas podem ser transferidos para outra pessoa.",
    "faq.general.q3": "Você fornece fatura?",
    "faq.general.a3": "Após o pagamento, você receberá um recibo, este não é um CFDI. Se você precisar de CFDI, por favor NÃO COMPRE no site, em vez disso envie-nos um e-mail para <a href='mailto:hola@nestorvazquez.com' target='_blank'>hola@nestorvazquez.com</a>",
    "faq.general.q4": "Como recebo meu certificado?",
    "faq.general.a4": "O certificado é entregue digitalmente por e-mail ao final do evento.",
    "speakers.miguel.qa1.question": "O que Miguel abordará em sua sessão?",
    "speakers.miguel.qa1.answer": "Miguel demonstrará como usar ferramentas de IA como ChatGPT e Claude para criar conteúdo otimizado para SEO que classifica no Google, desde pesquisa de palavras-chave até publicação final.",
    "speakers.miguel.qa2.question": "Esta sessão é adequada para iniciantes?",
    "speakers.miguel.qa2.answer": "Sim! Miguel explicará conceitos desde o início, enquanto também compartilha táticas avançadas para profissionais de SEO experientes.",
    "speakers.miguel.qa3.question": "Haverá exemplos práticos?",
    "speakers.miguel.qa3.answer": "Absolutamente. Miguel mostrará estudos de caso reais de sua agência e demonstrará fluxos de trabalho ao vivo usando IA para criação de conteúdo.",
    "speakers.eduardo.qa1.question": "O que é link building moderno?",
    "speakers.eduardo.qa1.answer": "Eduardo explicará como construir backlinks de alta qualidade através de Digital PR, guest posting e parcerias estratégicas que realmente fazem diferença em 2026.",
    "speakers.eduardo.qa2.question": "Eduardo compartilhará suas estratégias de WhitePress?",
    "speakers.eduardo.qa2.answer": "Sim! Ele revelará táticas comprovadas que sua equipe usa para garantir links de publicações autoritárias e como escalar campanhas de link building.",
    "speakers.eduardo.qa3.question": "Como posso aplicar isso ao meu negócio?",
    "speakers.eduardo.qa3.answer": "Eduardo fornecerá modelos acionáveis e estruturas de outreach que você pode implementar imediatamente, independentemente de sua indústria ou orçamento.",
    "speakers.nestor.qa1.question": "Quais ferramentas de automação Nestor abordará?",
    "speakers.nestor.qa1.answer": "Nestor demonstrará scripts Python para auditorias de SEO técnico, relatórios automatizados e tarefas de otimização em massa que economizam horas de trabalho manual.",
    "speakers.nestor.qa2.question": "Preciso de experiência em codificação?",
    "speakers.nestor.qa2.answer": "Nenhuma codificação necessária! Nestor fornecerá scripts prontos para usar e explicará como personalizá-los para suas necessidades específicas sem conhecimento de programação.",
    "speakers.nestor.qa3.question": "O que torna o SEO técnico 'avançado'?",
    "speakers.nestor.qa3.answer": "Nestor se concentra em estratégias de nível empresarial: renderização de JavaScript, otimização de Core Web Vitals, dados estruturados em escala e arquitetura de SEO internacional.",
    "agenda.title": "Agenda",
    "agenda.subtitle": "do Evento",
    "agenda.16_00": "Registro e Café de Boas-vindas",
    "agenda.16_00.desc": "Início do evento e boas-vindas.",
    "agenda.16_30.aleksandar": "Aleksandar Manok",
    "agenda.16_30.aleksandar.speaker": "Diretor Gerente",
    "agenda.16_30.aleksandar.desc": "SEO Authority as Capital - Turning Rankings into Real Asset Value.",
    "agenda.16_30.aleksandar.modal.title": "SEO AUTHORITY AS CAPITAL",
    "agenda.16_30.aleksandar.modal.description": "What if you didn't have to start from zero? Building or acquiring authority from day one can dramatically shift a project's growth curve. In today's market, even well-built sites that miss their scaling targets can attract serious buyer interest. Learn how to treat SEO authority like capital - making smarter strategic decisions and creating real liquidity from digital assets.",
    "agenda.16_45": "Jimena Sainz",
    "agenda.16_45.speaker": "Chefe de Marketing",
    "agenda.16_45.desc": "SEO no plano de marketing digital.",
    "agenda.17_30": "Miguel Rodriguez",
    "agenda.17_30.speaker": "Fundador Agencia SEO en Mexico",
    "agenda.17_30.desc": "Do prompt ao ranking: redação de SEO assistida por IA.",
    "agenda.17_45": "Eduardo Bortolotti Lopez",
    "agenda.17_45.speaker": "Líder de Equipe @ WhitePress",
    "agenda.17_45.desc": "De Pagerank para BrandRank",
    "agenda.17_45.modal.title": "BRANDRANK 2026",
    "agenda.17_45.modal.description": "Nesta palestra, Eduardo explicará como o link building mudou de uma abordagem centrada em PageRank para uma focada em sinais de marca. Ele introduzirá três proporções principais—Site Ratio, Focus Ratio e Brand Link Ratio—e mostrará como usá-las para avaliar a naturalidade do perfil de links e melhorar a visibilidade orgânica em 2026, tanto em SERPs tradicionais quanto em resultados de busca e respostas orientadas por IA.",
    "agenda.18_30": "Beerworking e Guacamole",
    "agenda.18_30.desc": "Networking de qualidade. Tacos, cerveja e guacamole com toda a comunidade de SEO.",
    "agenda.19_30": "Nestor Vazquez",
    "agenda.19_30.speaker": "Mentor e Estrategista de IA",
    "agenda.19_30.desc": "Do prompt ao ranking: redação de SEO assistida por IA.",
    "agenda.20_15": "Encerramento e Networking",
    "agenda.20_15.desc": "Espaço aberto para se conectar com palestrantes e participantes.",
    "location.title": "Local do Evento",
    "location.name": "Rooftop Hotel Roma Conesa",
    "location.address": "Monterrey 191, Centro Urbano Pdte. Juárez, Roma Nte., Cuauhtémoc, 06700 Cidade do México, CDMX",
    "location.city": "Cidade do México, México",
    "location.date": "26 de fevereiro de 2026",
    "location.time": "16:30 - 20:15",
    "location.map": "Ver no Google Maps",
    "tickets.title": "Não perca este evento",
    "tickets.subtitle": "SEO Guacamole",
    "tickets.limited": "Vagas Limitadas",
    "tickets.description": "Acesso completo a todas as conferências e sessão de networking por apenas",
    "tickets.price": "$50 USD",
    "tickets.cta": "COMPRAR INGRESSO AGORA",
    "tickets.secure": "Pagamento seguro via Stripe / PayPal",
    "partners.title": "Organizadores e",
    "partners.subtitle": "Parceiros",
    "partners.media": "Parceiros de Mídia",
    "partners.coming": "Em Breve",
    "footer.copyright": "Copyright 2026 SEO for LATAM Agency. Todos os direitos reservados.",
    "freeTicket.title": "Obtenha Seu Ingresso Grátis",
    "freeTicket.description": "Siga-nos nas redes sociais e reclame seu ingresso virtual gratuito!",
    "freeTicket.step1": "Siga-nos",
    "freeTicket.step1Desc": "Clique em qualquer plataforma abaixo para seguir nossa conta:",
    "freeTicket.step2": "Envie Comprovante",
    "freeTicket.step2Desc": "Envie-nos uma captura de tela ou DM comprovando que você seguiu:",
    "freeTicket.sendViaWhatsapp": "Enviar via WhatsApp",
    "freeTicket.step3": "Receba Seu Ingresso",
    "freeTicket.step3Desc": "Verificaremos seu seguimento e enviaremos um código de ingresso gratuito em até 24 horas!",
    "freeTicket.close": "Fechar",
    "pricing.free.title": "Ingresso Gratuito",
    "pricing.free.description": "Siga-nos nas redes sociais e obtenha um ingresso virtual gratuito!",
    "pricing.free.cta": "Reivindicar Ingresso Gratuito",
    "registration.title": "Registre-se para o Evento",
    "registration.name": "Nome",
    "registration.email": "E-mail",
    "registration.phone": "Telefone",
    "registration.coupon": "Código Promocional",
    "registration.couponPlaceholder": "Digite o código promocional",
    "registration.couponHint": "Tente TACOS10 para 10% de desconto!",
    "registration.fillAll": "Por favor, preencha todos os campos obrigatórios",
    "registration.redirectingToCheckout": "Redirecionando para checkout...",
    "registration.submit": "Registrar Agora",
    "registration.submitting": "Enviando...",
    "registration.success": "Registro bem-sucedido!",
    "registration.error": "Falha no registro. Por favor, tente novamente.",
    "countdown.title": "O Evento Começa Em",
    "countdown.subtitle": "Não perca o maior evento de SEO do México!",
    "countdown.days": "Dias",
    "countdown.hours": "Horas",
    "countdown.minutes": "Minutos",
    "countdown.seconds": "Segundos",
    "earlyBird.label": "OFERTA EARLY BIRD",
    "earlyBird.message": "Oferta por tempo limitado - Registre-se agora e economize!",
    "earlyBird.discount": "30% DE DESCONTO",
    "pricing.title": "Preços",
    "pricing.subtitle": "Garanta seu lugar pelo melhor preço. Não compre antes de ler a seção FAQ",
    "pricing.vip.badge": "MELHOR VALOR",
    "pricing.vip.title": "Admissão Geral",
    "pricing.vip.access": "Acesso Completo à Conferência",
    "pricing.vip.save": "Economize $50",
    "pricing.vip.feature1": "Acesso completo à conferência (26 de fevereiro)",
    "pricing.vip.feature2": "Beerworking e Tacos",
    "pricing.vip.feature3": "Todas as apresentações e slides dos palestrantes",
    "pricing.vip.feature4": "Certificado de Participação pela WhitePress",
    "pricing.vip.cta": "OBTER ADMISSÃO GERAL AGORA",
    "pricing.virtual.badge": "ECONOMIZE 50%",
    "pricing.virtual.title": "Admissão Virtual",
    "pricing.virtual.access": "Acesso à Conferência Virtual",
    "pricing.virtual.save": "Economize $30",
    "pricing.virtual.feature1": "Todas as apresentações e slides dos palestrantes",
    "pricing.virtual.feature2": "Certificado de Participação pela WhitePress",
    "pricing.virtual.cta": "OBTER ADMISSÃO VIRTUAL AGORA",
    "modal.title.vip": "Admissão Geral",
    "modal.title.virtual": "Admissão Virtual",
    "modal.title.regular": "Registro do Evento",
    "modal.description": "Preencha seus dados para garantir seu lugar no Evento SEO Guacamole",
    "modal.ticketType": "Tipo de Ingresso",
    "modal.price": "Preço Total",
    "modal.discount": "Desconto (10%)",
    "modal.submit": "Concluir Registro",
    "modal.processing": "Processando...",
    "ticket.success": "Ingresso comprado com sucesso!",
    "ticket.error": "Erro ao comprar ingresso",
    "contact.title": "Entre em Contato",
    "contact.subtitle": "Tem dúvidas? Estamos aqui para ajudar. Envie-nos uma mensagem e entraremos em contato o mais breve possível.",
    "contact.form.title": "Envie-nos uma Mensagem",
    "contact.form.name": "Seu Nome",
    "contact.form.namePlaceholder": "Digite seu nome completo",
    "contact.form.email": "Endereço de E-mail",
    "contact.form.emailPlaceholder": "seu@email.com",
    "contact.form.message": "Sua Mensagem",
    "contact.form.messagePlaceholder": "Diga-nos como podemos ajudá-lo...",
    "contact.form.submit": "Enviar Mensagem",
    "contact.form.sending": "Enviando...",
    "contact.form.success": "Mensagem enviada com sucesso! Entraremos em contato em breve.",
    "contact.form.error": "Erro ao enviar mensagem. Por favor, tente novamente.",
    "contact.info.email": "Envie-nos um E-mail",
    "contact.info.phone": "Ligue para Nós",
    "contact.info.whatsapp": "Mensagem no WhatsApp",
    "contact.info.location": "Visite-nos"
  },
  en: {
    "nav.language": "Español",
    "hero.edition": "CDMX Edition",
    "hero.title": "SEO GUACAMOLE",
    "hero.subtitle": "EVENT",
    "hero.description": "The SEO Conference, tacos and tequila, arrives in Mexico.",
    "hero.tagline": "Strategy, Networking and Coffee at the Rooftop Hotel Roma Conesa.",
    "hero.date": "26 Feb 2026",
    "hero.location": "CDMX",
    "hero.price": "",
    "hero.cta.primary": "Buy Ticket",
    "hero.cta.secondary": "Learn more",
    "about.title": "About the Event",
    "about.description": "<a href='https://www.linkedin.com/in/nestorvazquez/' rel='follow' target='_blank'>Nestor Vazquez</a> brings to Mexico City its series of international events. This special edition, The Guacamole, is designed to awaken your senses and your strategy.",
    "about.details": "In collaboration with <a href='https://seoforlatam.com/' rel='follow' target='_blank'>SEO for LATAM Agency</a>, we have created a space where the human and the artificial converge. We will talk about what really works today to rank in Google and how to integrate Artificial Intelligence (AI) into your workflows. No filler, just actionable tactics.",
    "about.speakers": "Expert Speakers",
    "about.duration": "Intensive Hours",
    "about.attendees": "VIP Attendees",
    "about.coffee": "Coffee",
    "speakers.title": "Our",
    "speakers.subtitle": "Speakers",
    "speakers.aleksandar.title": "Managing Director",
    "speakers.aleksandar.bio": "Aleks Manok Managing Director at Odys Marketplace, specializing in premium aged domains and digital asset strategy focusing on helping SEO professionals treat authority as capital from acquisition to monetization and exit strategy.",
    "speakers.jimena.title": "Head of Marketing",
    "speakers.jimena.bio": "Marketing iGaming Consultant",
    "speakers.nestor.title": "Mentor & Strategist",
    "speakers.nestor.bio": "Specialist in Local and Technical SEO. Master automation with Python to optimize processes in competitive US markets.",
    "speakers.eduardo.title": "Team Lead @ WhitePress",
    "speakers.eduardo.bio": "Passionate about SEO and music. Leads Link Building and Digital PR strategies that improve client visibility and authority.",
    "speakers.miguel.title": "Founder Agencia SEO en Mexico",
    "speakers.miguel.bio": "SEO Consultant with +10 years of experience and TOPSEO host. Offers customized solutions for companies of all sizes.",
    "speakers.qa.title": "Frequently Asked Questions",
    "faq.title": "Frequently Asked",
    "faq.subtitle": "Questions",
    "faq.description": "Everything you need to know about SEO Guacamole training",
    "faq.general.q1": "Is SEO Guacamole training suitable for my experience level?",
    "faq.general.a1": "SEO Guacamole welcomes SEO professionals at all levels—whether you're just starting your journey or you're a seasoned expert looking to sharpen your edge. Nestor Vazquez has designed this training with a mission: to guide you to your next level, wherever you currently stand. Beginners will gain foundational knowledge and proven strategies to build confidence, while intermediate and advanced practitioners will discover cutting-edge tactics based on real-world testing and results. No matter where you are in your SEO career, Nestor is committed to helping you level up with actionable insights you can implement immediately.",
    "faq.general.q2": "What's the refund policy?",
    "faq.general.a2": "Full refund available until February 1st. Simply email us and we'll process your refund, no questions asked. After February 1st, tickets are non-refundable but can be transferred to another person.",
    "faq.general.q3": "Do you provide invoice?",
    "faq.general.a3": "Once you pay you will have a receipt, this is not a CFDI. If you require CFDI please DO NOT BUY in the website, instead send us an email to <a href='mailto:hola@nestorvazquez.com' target='_blank'>hola@nestorvazquez.com</a>",
    "faq.general.q4": "How do I receive my certificate?",
    "faq.general.a4": "The certificate is delivered digitally via email at the end of the event.",
    "speakers.miguel.qa1.question": "What will Miguel cover in his session?",
    "speakers.miguel.qa1.answer": "Miguel will demonstrate how to use AI tools like ChatGPT and Claude to create SEO-optimized content that ranks in Google, from keyword research to final publication.",
    "speakers.miguel.qa2.question": "Is this session suitable for beginners?",
    "speakers.miguel.qa2.answer": "Yes! Miguel will explain concepts from the ground up while also sharing advanced tactics for experienced SEO professionals.",
    "speakers.miguel.qa3.question": "Will there be practical examples?",
    "speakers.miguel.qa3.answer": "Absolutely. Miguel will show real case studies from his agency and demonstrate live workflows using AI for content creation.",
    "speakers.eduardo.qa1.question": "What is modern link building?",
    "speakers.eduardo.qa1.answer": "Eduardo will explain how to build high-quality backlinks through Digital PR, guest posting, and strategic partnerships that actually move the needle in 2026.",
    "speakers.eduardo.qa2.question": "Will Eduardo share his WhitePress strategies?",
    "speakers.eduardo.qa2.answer": "Yes! He'll reveal proven tactics his team uses to secure links from authoritative publications and how to scale link building campaigns.",
    "speakers.eduardo.qa3.question": "How can I apply this to my business?",
    "speakers.eduardo.qa3.answer": "Eduardo will provide actionable templates and outreach frameworks you can implement immediately, regardless of your industry or budget.",
    "speakers.nestor.qa1.question": "What automation tools will Nestor cover?",
    "speakers.nestor.qa1.answer": "Nestor will demonstrate Python scripts for technical SEO audits, automated reporting, and bulk optimization tasks that save hours of manual work.",
    "speakers.nestor.qa2.question": "Do I need coding experience?",
    "speakers.nestor.qa2.answer": "No coding required! Nestor will provide ready-to-use scripts and explain how to customize them for your specific needs without programming knowledge.",
    "speakers.nestor.qa3.question": "What makes technical SEO 'advanced'?",
    "speakers.nestor.qa3.answer": "Nestor focuses on enterprise-level strategies: JavaScript rendering, Core Web Vitals optimization, structured data at scale, and international SEO architecture.",
    "agenda.title": "Event",
    "agenda.subtitle": "Agenda",
    "agenda.16_00": "Registration & Welcome Coffee",
    "agenda.16_00.desc": "Event start and welcome.",
    "agenda.16_30.aleksandar": "Aleksandar Manok",
    "agenda.16_30.aleksandar.speaker": "Managing Director",
    "agenda.16_30.aleksandar.desc": "SEO Authority as Capital - Turning Rankings into Real Asset Value.",
    "agenda.16_30.aleksandar.modal.title": "SEO AUTHORITY AS CAPITAL",
    "agenda.16_30.aleksandar.modal.description": "What if you didn't have to start from zero? Building or acquiring authority from day one can dramatically shift a project's growth curve. In today's market, even well-built sites that miss their scaling targets can attract serious buyer interest. Learn how to treat SEO authority like capital - making smarter strategic decisions and creating real liquidity from digital assets.",
    "agenda.16_45": "Jimena Sainz",
    "agenda.16_45.speaker": "Head of Marketing",
    "agenda.16_45.desc": "SEO in the digital marketing plan.",
    "agenda.17_30": "Miguel Rodriguez",
    "agenda.17_30.speaker": "Founder SEO Agency in Mexico",
    "agenda.17_30.desc": "From prompt to ranking: SEO writing assisted with AI.",
    "agenda.17_45": "Eduardo Bortolotti Lopez",
    "agenda.17_45.speaker": "Team Lead @ WhitePress",
    "agenda.17_45.desc": "From Pagerank to BrandRank",
    "agenda.17_45.modal.title": "BRANDRANK 2026",
    "agenda.17_45.modal.description": "In this talk, Eduardo will explain how link building has shifted from a PageRank-centric approach to one focused on Brand signals. He will introduce three key ratios—Site Ratio, Focus Ratio, and Brand Link Ratio—and show how to use them to assess link profile naturalness and improve organic visibility in 2026, both in traditional SERPs and in AI-driven search results and answers.",
    "agenda.18_30": "Beerworking & Guacamole",
    "agenda.18_30.desc": "Quality networking. Tacos, beer, and guacamole with the entire SEO community.",
    "agenda.19_30": "Nestor Vazquez",
    "agenda.19_30.speaker": "Mentor & AI Strategist",
    "agenda.19_30.desc": "From prompt to ranking: SEO writing assisted with AI.",
    "agenda.20_15": "Closing & Networking",
    "agenda.20_15.desc": "Open space to connect with speakers and attendees.",
    "location.title": "Event Location",
    "location.name": "Rooftop Hotel Roma Conesa",
    "location.address": "Monterrey 191, Centro Urbano Pdte. Juárez, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX",
    "location.city": "Mexico City, Mexico",
    "location.date": "26 February, 2026",
    "location.time": "16:30 - 20:15",
    "location.map": "View on Google Maps",
    "tickets.title": "Don't miss this event",
    "tickets.subtitle": "SEO Guacamole",
    "tickets.limited": "Limited Spots",
    "tickets.description": "Full access to all conferences, and networking session for only",
    "tickets.price": "$50 USD",
    "tickets.cta": "BUY TICKET NOW",
    "tickets.secure": "Secure payment via Stripe / PayPal",
    "partners.title": "Organizers &",
    "partners.subtitle": "Partners",
    "partners.media": "Media Partners",
    "partners.coming": "Coming Soon",
    "footer.copyright": "Copyright 2026 SEO for LATAM Agency. All rights reserved.",
    "freeTicket.title": "Get Your Free Ticket",
    "freeTicket.description": "Follow us on social media and claim your free virtual ticket!",
    "freeTicket.step1": "Follow Us",
    "freeTicket.step1Desc": "Click on any platform below to follow our account:",
    "freeTicket.step2": "Send Proof",
    "freeTicket.step2Desc": "Send us a screenshot or DM proof that you followed:",
    "freeTicket.sendViaWhatsapp": "Send via WhatsApp",
    "freeTicket.step3": "Get Your Ticket",
    "freeTicket.step3Desc": "We'll verify your follow and send you a free ticket code within 24 hours!",
    "freeTicket.close": "Close",
    "pricing.free.title": "Free Ticket",
    "pricing.free.description": "Follow us on social media and get a free virtual ticket!",
    "pricing.free.cta": "Claim Free Ticket",
    "registration.title": "Register for the Event",
    "registration.name": "Name",
    "registration.email": "Email",
    "registration.phone": "Phone",
    "registration.coupon": "Promo Code",
    "registration.couponPlaceholder": "Enter promo code",
    "registration.couponHint": "Try TACOS10 for 10% off!",
    "registration.fillAll": "Please fill in all required fields",
    "registration.redirectingToCheckout": "Redirecting to checkout...",
    "registration.submit": "Register Now",
    "registration.submitting": "Submitting...",
    "registration.success": "Registration successful!",
    "registration.error": "Registration failed. Please try again.",
    "countdown.title": "Event Starts In",
    "countdown.subtitle": "Don't miss the biggest SEO event in Mexico!",
    "countdown.days": "Days",
    "countdown.hours": "Hours",
    "countdown.minutes": "Minutes",
    "countdown.seconds": "Seconds",
    "earlyBird.label": "EARLY BIRD SPECIAL",
    "earlyBird.message": "Limited time offer - Register now and save!",
    "earlyBird.discount": "30% OFF",
    "pricing.title": "Pricing",
    "pricing.subtitle": "Secure your spot at the best price. Do not buy before reading the FAQ section",
    "pricing.vip.badge": "BEST VALUE",
    "pricing.vip.title": "General Admission",
    "pricing.vip.access": "Full Conference Access",
    "pricing.vip.save": "Save $50",
    "pricing.vip.feature1": "Full conference access (Feb 26th)",
    "pricing.vip.feature2": "Beerworking & Tacos",
    "pricing.vip.feature3": "All speaker presentations & slides",
    "pricing.vip.feature4": "Participation Certificate by WhitePress",
    "pricing.vip.cta": "GET GENERAL ADMISSION NOW",
    "pricing.virtual.badge": "SAVE 50%",
    "pricing.virtual.title": "Virtual Admission",
    "pricing.virtual.access": "Virtual Conference Access",
    "pricing.virtual.save": "Save $30",
    "pricing.virtual.feature1": "All speaker presentations & slides",
    "pricing.virtual.feature2": "Participation Certificate by WhitePress",
    "pricing.virtual.cta": "GET VIRTUAL ADMISSION NOW",
    "modal.title.vip": "General Admission",
    "modal.title.virtual": "Virtual Admission",
    "modal.title.regular": "Event Registration",
    "modal.description": "Fill in your details to secure your spot at SEO Guacamole Event",
    "modal.ticketType": "Ticket Type",
    "modal.price": "Total Price",
    "modal.discount": "Discount (10%)",
    "modal.submit": "Complete Registration",
    "modal.processing": "Processing...",
    "ticket.success": "Ticket purchased successfully!",
    "ticket.error": "Error purchasing ticket",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions? We're here to help. Send us a message and we'll get back to you as soon as possible.",
    "contact.form.title": "Send us a Message",
    "contact.form.name": "Your Name",
    "contact.form.namePlaceholder": "Enter your full name",
    "contact.form.email": "Email Address",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.message": "Your Message",
    "contact.form.messagePlaceholder": "Tell us how we can help you...",
    "contact.form.submit": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Message sent successfully! We'll get back to you soon.",
    "contact.form.error": "Error sending message. Please try again.",
    "contact.info.email": "Email Us",
    "contact.info.phone": "Call Us",
    "contact.info.whatsapp": "Message on WhatsApp",
    "contact.info.location": "Visit Us"
  },
  es: {
    "nav.language": "English",
    "faq.title": "Preguntas",
    "faq.subtitle": "Frecuentes",
    "faq.description": "Todo lo que necesitas saber sobre el entrenamiento SEO Guacamole",
    "faq.general.q1": "¿El entrenamiento SEO Guacamole es adecuado para mi nivel de experiencia?",
    "faq.general.a1": "SEO Guacamole da la bienvenida a profesionales SEO de todos los niveles, ya sea que estes comenzando tu viaje o seas un experto experimentado buscando afilar tu ventaja. Nestor Vazquez ha disenado este entrenamiento con una mision: guiarte a tu siguiente nivel, donde sea que te encuentres actualmente. Los principiantes obtendran conocimientos fundamentales y estrategias comprobadas para construir confianza, mientras que los practicantes intermedios y avanzados descubriran tacticas de vanguardia basadas en pruebas y resultados del mundo real. No importa donde estes en tu carrera SEO, Nestor esta comprometido a ayudarte a subir de nivel con conocimientos accionables que puedes implementar inmediatamente.",
    "faq.general.q2": "¿Cual es la politica de reembolso?",
    "faq.general.a2": "Reembolso completo disponible hasta el 1 de febrero. Simplemente envianos un correo electronico y procesaremos tu reembolso, sin hacer preguntas. Despues del 1 de febrero, los boletos no son reembolsables pero pueden transferirse a otra persona.",
    "faq.general.q3": "¿Proporcionan factura?",
    "faq.general.a3": "Una vez que pagues tendras un recibo, esto no es un CFDI. Si requieres CFDI por favor NO COMPRES en el sitio web, en su lugar envianos un correo electronico a <a href='mailto:hola@nestorvazquez.com' target='_blank'>hola@nestorvazquez.com</a>",
    "faq.general.q4": "¿Cómo recibo mi certificado?",
    "faq.general.a4": "El certificado se entrega digitalmente por correo electrónico al final del evento.",
    "hero.edition": "Edicion CDMX",
    "hero.title": "SEO GUACAMOLE",
    "hero.subtitle": "EVENT",
    "hero.description": "La Conferencia SEO, tacos y tequila, llega a Mexico.",
    "hero.tagline": "Estrategia, Networking y Cafeina en el Rooftop Hotel Roma Conesa.",
    "hero.date": "26 Feb 2026",
    "hero.location": "CDMX",
    "hero.price": "",
    "hero.cta.primary": "Comprar Entrada",
    "hero.cta.secondary": "Conocer mas",
    "about.title": "Sobre el Evento",
    "about.description": "<a href='https://www.linkedin.com/in/nestorvazquez/' rel='follow' target='_blank'>Nestor Vazquez</a> trae a la Ciudad de Mexico su serie de eventos internacionales. Esta edicion especial, The Guacamole, esta disenada para despertar tus sentidos y tu estrategia.",
    "about.details": "En colaboracion con <a href='https://seoforlatam.com/' rel='follow' target='_blank'>SEO for LATAM Agency</a>, hemos creado un espacio donde convergen lo humano y lo artificial. Hablaremos de lo que realmente funciona hoy para posicionar en Google y como integrar la Inteligencia Artificial (IA) en tus flujos de trabajo. Sin rellenos, solo tacticas accionables.",
    "about.speakers": "Ponentes Expertos",
    "about.duration": "Horas Intensivas",
    "about.attendees": "Asistentes VIP",
    "about.coffee": "Cafe",
    "speakers.title": "Nuestros",
    "speakers.subtitle": "Speakers",
    "speakers.aleksandar.title": "Director Gerente",
    "speakers.aleksandar.bio": "Aleks Manok Director Gerente en Odys Marketplace, especializado en dominios envejecidos premium y estrategia de activos digitales enfocado en ayudar a profesionales de SEO a tratar la autoridad como capital desde la adquisición hasta la monetización y estrategia de salida.",
    "speakers.jimena.title": "Jefa de Marketing",
    "speakers.jimena.bio": "Consultora de Marketing en iGaming",
    "speakers.nestor.title": "Mentor & Estratega",
    "speakers.nestor.bio": "Especialista en SEO Local y Tecnico. Domina la automatizacion con Python para optimizar procesos en mercados competitivos de EE.UU.",
    "speakers.eduardo.title": "Team Lead @ WhitePress",
    "speakers.eduardo.bio": "Apasionado del SEO y la musica. Lidera estrategias de Link Building y PR Digital que mejoran la visibilidad y autoridad de los clientes.",
    "speakers.miguel.title": "Fundador Agencia SEO en Mexico",
    "speakers.miguel.bio": "Consultor SEO con +10 anos de experiencia y host de TOPSEO. Ofrece soluciones personalizadas para empresas de todos los tamanos.",
    "speakers.qa.title": "Preguntas Frecuentes",
    "speakers.miguel.qa1.question": "¿Que cubrira Miguel en su sesion?",
    "speakers.miguel.qa1.answer": "Miguel demostrara como usar herramientas de IA como ChatGPT y Claude para crear contenido optimizado para SEO que posiciona en Google, desde la investigacion de palabras clave hasta la publicacion final.",
    "speakers.miguel.qa2.question": "¿Esta sesion es adecuada para principiantes?",
    "speakers.miguel.qa2.answer": "Si! Miguel explicara los conceptos desde cero mientras tambien comparte tacticas avanzadas para profesionales SEO experimentados.",
    "speakers.miguel.qa3.question": "¿Habra ejemplos practicos?",
    "speakers.miguel.qa3.answer": "Absolutamente. Miguel mostrara casos de estudio reales de su agencia y demostrara flujos de trabajo en vivo usando IA para creacion de contenido.",
    "speakers.eduardo.qa1.question": "¿Que es el link building moderno?",
    "speakers.eduardo.qa1.answer": "Eduardo explicara como construir backlinks de alta calidad a traves de Digital PR, guest posting y alianzas estrategicas que realmente marcan la diferencia en 2026.",
    "speakers.eduardo.qa2.question": "¿Eduardo compartira sus estrategias de WhitePress?",
    "speakers.eduardo.qa2.answer": "Si! Revelara tacticas comprobadas que su equipo usa para conseguir enlaces de publicaciones autorizadas y como escalar campanas de link building.",
    "speakers.eduardo.qa3.question": "¿Como puedo aplicar esto a mi negocio?",
    "speakers.eduardo.qa3.answer": "Eduardo proporcionara plantillas accionables y marcos de outreach que puedes implementar inmediatamente, sin importar tu industria o presupuesto.",
    "speakers.nestor.qa1.question": "¿Que herramientas de automatizacion cubrira Nestor?",
    "speakers.nestor.qa1.answer": "Nestor demostrara scripts de Python para auditorias SEO tecnicas, reportes automatizados y tareas de optimizacion masiva que ahorran horas de trabajo manual.",
    "speakers.nestor.qa2.question": "¿Necesito experiencia en programacion?",
    "speakers.nestor.qa2.answer": "No se requiere programacion! Nestor proporcionara scripts listos para usar y explicara como personalizarlos para tus necesidades especificas sin conocimientos de programacion.",
    "speakers.nestor.qa3.question": "¿Que hace que el SEO tecnico sea 'avanzado'?",
    "speakers.nestor.qa3.answer": "Nestor se enfoca en estrategias de nivel empresarial: renderizado de JavaScript, optimizacion de Core Web Vitals, datos estructurados a escala y arquitectura SEO internacional.",
    "agenda.title": "Agenda del",
    "agenda.subtitle": "Evento",
    "agenda.16_00": "Registro & Welcome Coffee",
    "agenda.16_00.desc": "Inicio del evento y bienvenida.",
    "agenda.16_30.aleksandar": "Aleksandar Manok",
    "agenda.16_30.aleksandar.speaker": "Director Gerente",
    "agenda.16_30.aleksandar.desc": "SEO Authority as Capital - Turning Rankings into Real Asset Value.",
    "agenda.16_30.aleksandar.modal.title": "SEO AUTHORITY AS CAPITAL",
    "agenda.16_30.aleksandar.modal.description": "What if you didn't have to start from zero? Building or acquiring authority from day one can dramatically shift a project's growth curve. In today's market, even well-built sites that miss their scaling targets can attract serious buyer interest. Learn how to treat SEO authority like capital - making smarter strategic decisions and creating real liquidity from digital assets.",
    "agenda.16_45": "Jimena Sainz",
    "agenda.16_45.speaker": "Jefa de Marketing",
    "agenda.16_45.desc": "SEO en el plan de marketing digital.",
    "agenda.17_30": "Miguel Rodriguez",
    "agenda.17_30.speaker": "Fundador Agencia SEO en México",
    "agenda.17_30.desc": "Del prompt al ranking: redacción SEO asistida con IA.",
    "agenda.17_45": "Eduardo Bortolotti Lopez",
    "agenda.17_45.speaker": "Team Lead @ WhitePress",
    "agenda.17_45.desc": "From Pagerank to BrandRank",
    "agenda.17_45.modal.title": "BRANDRANK 2026",
    "agenda.17_45.modal.description": "En esta charla, Eduardo explicará cómo la construcción de enlaces ha pasado de un enfoque centrado en PageRank a uno enfocado en señales de marca. Introducirá tres ratios clave: Site Ratio, Focus Ratio y Brand Link Ratio, y mostrará cómo usarlos para evaluar la naturalidad del perfil de enlaces y mejorar la visibilidad orgánica en 2026, tanto en SERPs tradicionales como en resultados de búsqueda impulsados por IA y respuestas.",
    "agenda.18_30": "Beerworking & Guacamole",
    "agenda.18_30.desc": "Networking de calidad. Tacos, cerveza y guacamole con toda la comunidad SEO.",
    "agenda.19_30": "Nestor Vazquez",
    "agenda.19_30.speaker": "Mentor & AI Strategist",
    "agenda.19_30.desc": "Del prompt al ranking: Redaccion SEO asistida con IA.",
    "agenda.20_15": "Closing & Networking",
    "agenda.20_15.desc": "Espacio abierto para conectar con ponentes y asistentes.",
    "location.title": "Ubicacion del Evento",
    "location.name": "Rooftop Hotel Roma Conesa",
    "location.address": "Monterrey 191, Centro Urbano Pdte. Juárez, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX",
    "location.city": "Ciudad de Mexico, Mexico",
    "location.date": "26 de Febrero, 2026",
    "location.time": "16:30 - 20:15",
    "location.map": "Ver en Google Maps",
    "tickets.title": "No te pierdas este evento",
    "tickets.subtitle": "SEO Guacamole",
    "tickets.limited": "Plazas Limitadas",
    "tickets.description": "Acceso completo a todas las conferencias, y sesión de networking por solo",
    "tickets.price": "$50 USD",
    "tickets.cta": "COMPRAR ENTRADA AHORA",
    "tickets.secure": "Pago seguro via Stripe / PayPal",
    "partners.title": "Organizadores &",
    "partners.subtitle": "Partners",
    "partners.media": "Media Partners",
    "partners.coming": "Proximamente",
    "footer.copyright": "Copyright 2026 SEO for LATAM Agency. Todos los derechos reservados.",
    "freeTicket.title": "Obtén Tu Ingreso Gratis",
    "freeTicket.description": "¡Síguenos en redes sociales y reclama tu ingreso virtual gratuito!",
    "freeTicket.step1": "Síguenos",
    "freeTicket.step1Desc": "Haz clic en cualquier plataforma a continuación para seguir nuestra cuenta:",
    "freeTicket.step2": "Envía Comprobante",
    "freeTicket.step2Desc": "Envíanos una captura de pantalla o DM comprobando que nos seguiste:",
    "freeTicket.sendViaWhatsapp": "Enviar por WhatsApp",
    "freeTicket.step3": "Obtén Tu Ingreso",
    "freeTicket.step3Desc": "¡Verificaremos tu seguimiento y te enviaremos un código de ingreso gratuito en 24 horas!",
    "freeTicket.close": "Cerrar",
    "pricing.free.title": "Ingreso Gratuito",
    "pricing.free.description": "¡Síguenos en redes sociales y obtén un ingreso virtual gratuito!",
    "pricing.free.cta": "Reclamar Ingreso Gratuito",
    "registration.title": "Registrate al Evento",
    "registration.name": "Nombre",
    "registration.email": "Correo Electronico",
    "registration.phone": "Telefono",
    "registration.coupon": "Código Promocional",
    "registration.couponPlaceholder": "Ingresa código promocional",
    "registration.couponHint": "¡Intenta TACOS10 para 10% de descuento!",
    "registration.fillAll": "Por favor completa todos los campos requeridos",
    "registration.redirectingToCheckout": "Redirigiendo al pago...",
    "registration.submit": "Registrarse Ahora",
    "registration.submitting": "Enviando...",
    "registration.success": "Registro exitoso!",
    "registration.error": "Error al registrarse. Por favor intenta de nuevo.",
    "countdown.title": "El Evento Comienza En",
    "countdown.subtitle": "No te pierdas el evento SEO mas grande de Mexico!",
    "countdown.days": "Dias",
    "countdown.hours": "Horas",
    "countdown.minutes": "Minutos",
    "countdown.seconds": "Segundos",
    "earlyBird.label": "OFERTA ESPECIAL",
    "earlyBird.message": "Oferta por tiempo limitado - Registrate ahora y ahorra!",
    "earlyBird.discount": "30% DE DESCUENTO",
    "pricing.title": "Precios",
    "pricing.subtitle": "Asegura tu lugar al mejor precio. No compres antes de leer la seccion de preguntas frecuentes",
    "pricing.vip.badge": "MEJOR VALOR",
    "pricing.vip.title": "Admisión General",
    "pricing.vip.access": "Acceso Completo a la Conferencia",
    "pricing.vip.save": "Ahorra $50",
    "pricing.vip.feature1": "Acceso completo a la conferencia (26 de febrero)",
    "pricing.vip.feature2": "Beerworking & Tacos",
    "pricing.vip.feature3": "Todas las presentaciones y diapositivas de los ponentes",
    "pricing.vip.feature4": "Certificado de Participación por WhitePress",
    "pricing.vip.cta": "OBTENER ADMISIÓN GENERAL AHORA",
    "pricing.virtual.badge": "AHORRA 50%",
    "pricing.virtual.title": "Admisión Virtual",
    "pricing.virtual.access": "Acceso a la Conferencia Virtual",
    "pricing.virtual.save": "Ahorra $30",
    "pricing.virtual.feature1": "Todas las presentaciones y diapositivas de los ponentes",
    "pricing.virtual.feature2": "Certificado de Participación por WhitePress",
    "pricing.virtual.cta": "OBTENER ADMISIÓN VIRTUAL AHORA",
    "modal.title.vip": "Admisión General",
    "modal.title.virtual": "Admisión Virtual",
    "modal.title.regular": "Registro al Evento",
    "modal.description": "Completa tus datos para asegurar tu lugar en el Evento SEO Guacamole",
    "modal.ticketType": "Tipo de Boleto",
    "modal.price": "Precio Total",
    "modal.discount": "Descuento (10%)",
    "modal.submit": "Completar Registro",
    "modal.processing": "Procesando...",
    "ticket.success": "Boleto comprado exitosamente!",
    "ticket.error": "Error al comprar boleto",
    "contact.title": "Contáctanos",
    "contact.subtitle": "¿Tienes preguntas? Estamos aquí para ayudarte. Envíanos un mensaje y te responderemos lo antes posible.",
    "contact.form.title": "Envíanos un Mensaje",
    "contact.form.name": "Tu Nombre",
    "contact.form.namePlaceholder": "Ingresa tu nombre completo",
    "contact.form.email": "Correo Electrónico",
    "contact.form.emailPlaceholder": "tu@email.com",
    "contact.form.message": "Tu Mensaje",
    "contact.form.messagePlaceholder": "Cuéntanos cómo podemos ayudarte...",
    "contact.form.submit": "Enviar Mensaje",
    "contact.form.sending": "Enviando...",
    "contact.form.success": "¡Mensaje enviado exitosamente! Te responderemos pronto.",
    "contact.form.error": "Error al enviar mensaje. Por favor intenta de nuevo.",
    "contact.info.email": "Envíanos un Email",
    "contact.info.phone": "Llámanos",
    "contact.info.whatsapp": "Mensajea en WhatsApp",
    "contact.info.location": "Visítanos"
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Detect user's country from IP and set language accordingly
    if (typeof window !== "undefined") {
      const userCountry = (window as any).__COUNTRY__;
      if (userCountry === "BR") {
        return "pt";
      } else if (["MX", "ES", "AR", "CO", "CL", "PE"].includes(userCountry)) {
        return "es";
      }
    }
    return "en";
  });

  // Detect country on component mount
  useEffect(() => {
    const detectCountry = async () => {
      try {
        const response = await fetch("https://ipapi.co/json/");
        const data = await response.json();
        const country = data.country_code;
        (window as any).__COUNTRY__ = country;
        
        if (country === "BR") {
          setLanguage("pt");
        } else if (["MX", "ES", "AR", "CO", "CL", "PE"].includes(country)) {
          setLanguage("es");
        }
      } catch (error) {
        console.log("Could not detect country");
      }
    };
    
    detectCountry();
  }, []);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };



  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
